### PR TITLE
DDF-1288: updated jacoco configuration.

### PR DESCRIPTION
**Pull request by djblue**
@lessarderic @andrewkfiedler please review.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-libs/7)

### CODE REVIEW

**Comment by lessarderic** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[httpproxy/pom.xml, line 92 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-libs/7#-JsS3okdYRvmpFBjkNar)** ([raw file](https://github.com/codice/ddf-libs/blob/22d92e2d9929eb98821a187fff5b544e110db147/httpproxy/pom.xml#L92)):</sup>
We should put this configuration in the sub-projects (proxy-camel-route and proxy-camel-servlet) instead, especially since proxy-camel-servlet has a couple unit tests and should already have some code coverage.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-libs/7)

**Comment by lessarderic** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-libs/7)

**Comment by andrew-fiedler** [comment]
@andrew-fiedler

**Comment by andrew-fiedler** [comment]
Note: have to have this change for the jacoco to actually run.

https://github.com/codice/ddf-parent/pull/26

**Comment by andrew-fiedler** [comment]
:+1:  built and tested (with the other pull request changes)

**Comment by shaundmorris** [comment]
Verified build and integration tests.

**Pull request merged**
