### PR TITLE
DDF-1197 created an HTTP to HTTPS proxy to use for legacy clients

### PR DESCRIPTION
**Pull request by stustison**
- added new HTTP to HTTPS camel proxy service
 - added integration test for anonymous SOAP HTTP access
 - disabled HTTP in pax web configuration file

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-libs/5)

### CODE REVIEW

**Comment by stustison** [comment]
@pklinef @lessarderic

**Comment by stustison** [comment]
@shaundmorris

**Comment by lessarderic** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- httpproxy/proxy-camel-route/pom.xml @ r1
- httpproxy/proxy-camel-route/src/main/java/org/codice/proxy/http/HttpProxyServiceImpl.java @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-libs/5)

**Comment by pklinef** [comment]
:+1:

**Pull request merged**
